---
title: "realpage analysis"
author: "Mason Gatewood"
date: '2023-01-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Load in Tidyverse for data analysis and zipcodeR to geocode the zipcodes captured by BuiltWith
```{r}
library(tidyverse)
library(zipcodeR)
```

```{r}
real_page <- read.csv("rp-data.CSV")

real_page <- real_page %>%  select(Domain, Telephones, Emails, Twitter, Facebook, LinkedIn, Google, Pinterest, GitHub, Instagram, Vk, Vimeo, Youtube, TikTok, People, City, State, Zip, Country, Last.Indexed)

glimpse(real_page)
```
```{r}
zip_data <- zip_code_db
glimpse(zip_data)
```

```{r}
joined_data <- real_page %>% left_join(zip_data, by=c('Zip' = 'zipcode'))
glimpse(joined_data)
```

```{r}
joined_data %>% 
  ggplot(aes(x = lng, y = lat)) +
  geom_point() +
  borders("state") +
  theme_void()
```
```{r}
joined_data %>% 
  group_by(Zip, major_city, state, lat, lng) %>% 
  summarize(count = n()) %>% 
  drop_na(major_city) %>% 
  ggplot(aes(x = lng, y = lat, size = count)) +
  geom_point() +
  borders("state") +
  theme_void()
```

```{r}
write.csv(joined_data, "joined_data.csv")
```

